### ISSUE TITLE
[Toolbar] Removing shadow from toolbar

### ISSUE THREAD

**Issue by xigolle** [xotahal/react-native-material-ui#115]
Dear, 

Is there a possibility that we can make the shadow of the toolbar transparent. I have been looking through the documentation but I could not find anyway to do it. 
At this moment I have the following code but doesn't seem to do anything. 
            style ={{
                container:{shadowColor: '#F00'},
            }}

**Comment by xotahal** [comment]
```js
style ={{
    container:{ elevation: 0 },
}}
```
