### ISSUE TITLE
[FAB] Button cut off on the bottom side

### ISSUE THREAD

**Issue by xigolle** [xotahal/react-native-material-ui#119]
Dear, 

I am using the FAB currently in my project but I noticed that there is something strange (probably with the shadow ) with the button. 
It seems that the bottom side of the button is somehow cut off. 
Is there a way to solve this or is there something happening with the rendering? 

With shadow:

[![FAB cut off.jpg](https://s11.postimg.org/bnr5i1nar/FAB_cut_off.jpg)](https://postimg.org/image/orwpuqfcf/)

Without shadow:

[![FAB cut off without shadow.jpg](https://s10.postimg.org/ocsnvfctl/FAB_cut_off_without_shadow.jpg)](https://postimg.org/image/57pelny5h/)

Hope somebody can help me fix this problem.

**Comment by HofmannZ** [comment]
Yeah only happens on android I see, just need some margin on the bottom I think.

**Comment by xigolle** [comment]
@HofmannZ Where should I put this margin than ? Because if I put it on the outside of the container I still get the same problem only the button somewhat higher. So I don't know how I can put margin on the inner container (so to say).

**Comment by HofmannZ** [comment]
The styles on the FAB would look something like this: `{ container: { marginBottom: 16 }`. You can change the margin to anything you like, I know 16 works pretty good for us. I'm opening a PR soon Because it seems to be a little bug.

**Comment by xigolle** [comment]
Thanks a lot @HofmannZ I used `{ container: { marginBottom: 2 }` and that looks pretty good now 👍 Is there a way to compensate for this change . Because this moves the button 2 dp up @HofmannZ  :)

**Comment by HofmannZ** [comment]
You could translate the FAB with 2 dp ex.
```js
{
  container: {
    transform: [{
      traslateY: -2,
    }],
  },
}
```
I hope that helps you out 🤙🏼

**Comment by xotahal** [comment]
This one is fixed, but we still need to redesign ActionButton ...
