### ISSUE TITLE
Possibility to use font awesome icons

### ISSUE THREAD

**Issue by anttilehtonen** [xotahal/react-native-material-ui#124]
Hi,
I like this library a lot.
I would like to use font awesome icons that are in react-native-vector-icons. 
Is this possible?

**Comment by NewOldMax** [comment]
For some components you can pass you custom icon element instead of icon name (for example, in Floating Action Button).

**Comment by piranna** [comment]
> For some components you can pass you custom icon element instead of icon name (for example, in Floating Action Button).

Can you provide an example of how to do that?

**Comment by NewOldMax** [comment]
@piranna It works for action items in [ActionButton](https://github.com/xotahal/react-native-material-ui/blob/master/src/ActionButton/ActionButton.react.js#L30)

**Comment by BorlandFA** [comment]
And what about the other components where is not possible to pass a custom Icon element, like the drawer sections? I think It would be great to be able to configure the icon type you want like in React Native Base.

**Comment by xotahal** [comment]
It is possible now - https://github.com/xotahal/react-native-material-ui/releases/tag/1.30.1

**Comment by BorlandFA** [comment]
Awesome! Thx!!
