### ISSUE TITLE
Font family Roboto breaks on IOS

### ISSUE THREAD

**Issue by iRoachie** [xotahal/react-native-material-ui#132]
Newest version 1.9.0 breaks IOS because of 'Roboto' fontFamily

![simulator screen shot apr 21 2017 2 42 43 pm](https://cloud.githubusercontent.com/assets/5962998/25291618/cbc18b14-26a0-11e7-8bf1-1e3e6ae7ad7a.png)

**Comment by iRoachie** [comment]
Should probably mention including Roboto in the setup instructions or leave the default for iOS which is 'System'.

@xotahal Which do you prefer?

**Comment by xotahal** [comment]
@iRoachie Think we should follow the Material Design, so we should mention including Roboto in the setup ..

**Comment by ydykevin** [comment]
I met the same problem on IOS with version 6.1.0. Tried link and add library, but Roboto font is just not found.

Then I discover this error only occurs when I use "Toolbar".

Here is how I solve this.
1. I download the demo app.
2. Find all "Roboto" reference.
3. Based on my search, there are two places. One in "info.plist", and the other one in "project.pbxproj".
4. Copy all "Roboto" references to your project at corresponding places.
5. Copy "Asset" folder (in demo project root) to your project root.
6. Clean your project and rebuild.

Then it works fine to me.

I hope someone can fix this or remove the usage of Roboto if necessary.

**Comment by bdelville** [comment]
I had the same issue on iOS after following the step recommended in the documentation:
https://medium.com/@danielskripnik/how-to-add-and-remove-custom-fonts-in-react-native-b2830084b0e4

The font were indeed added into "Build Phase / Copy Bundle Resource", but not in the Info.plist
Adding the fonts into info.plist solved the issue
