### ISSUE TITLE
COLOR undefined when rendering directly

### ISSUE THREAD

**Issue by MewX** [xotahal/react-native-material-ui#134]
import * as COLOR from "react-native-material-ui";
    ...
    render() {
        console.log(COLOR.blue700);
    }

The result is:

```
undefined
```

I'm not sure whether it is safe to change the `import` into:

    import {blue500} from "react-native-material-ui/src/styles/colors";

However, only in this way can it output the constant correctly. But why `COLOR.blue700` doesn't work?

Thanks at first!

**Comment by xotahal** [comment]
import { COLOR } from 'react-native-material-ui'
