### ISSUE TITLE
Question - Toolbar - toolbar is always top??

### ISSUE THREAD

**Issue by delia-m** [xotahal/react-native-material-ui#145]
I should cover toolbar with translucent view but toolbar always place on the top so I can't cover it in **android** especially. 

Any way to handle this??

**Comment by xotahal** [comment]
The main reason why I've done this library was that you can do whatever you want with style of components.

So you can pass `<Toolbar style={{ container: { position: 'absolute' }} />` - just check the source code a change style via style prop
