### ISSUE TITLE
Trouble initializing the Components

### ISSUE THREAD

**Issue by chstavridis** [xotahal/react-native-material-ui#16]
Hello, i am _a new not experience user_ of React Native and i would like some help, about how could i use your Materials Ui components. Your demo is simply amazing! 
Apparently at first, i have to create a new project and after i have to execute in 

> cmd npm i react-native-material-ui --save

 and copy the fonts icons

> ./node_modules/react-native-vector-icons/Fonts/MaterialIcons.ttf -> ./android/app/src/main/assets/fonts.

After these steps i do not understand what exactly i have to do, to use your components. _Could i use your demo like a starting project_?

Thanks a lot and sorry if my questions are "dummy" :)!

**Comment by xotahal** [comment]
Hi @chstavridis,

I followed a [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html) instructions when I was creating the demo app. So try it as well ;)

You can use demo app like your starting project, but there are definitely better boilerplates - like [este.js](https://github.com/este/este) for example.

Then you can use our components in the same way as in [demo app](https://github.com/xotahal/react-native-material-ui-demo-app).

```js
render() {
  return <Button text="hello world" />
}
```

Let me know how it goes ;)
