### ISSUE TITLE
ListItem does not fully support dynamic number of lines

### ISSUE THREAD

**Issue by jjgarzella** [xotahal/react-native-material-ui#161]
Right now, the ListItem component doesn't render a long string on multiple lines when the `numberOfLines` prop is set to `'dynamic'`, it simply truncates the string. To fix this (without thinking too hard about what happens with secondary and tertiary text), the `1` in line 302 of ListItem.react.js would need to be changed to `numberOfLines === 'dynamic' ? 0 : 1`.  I am willing to fork and make a pull request to fix this if necessary.

**Comment by Asthor** [comment]
hello @jjgarzella did you forked it?

**Comment by jjgarzella** [comment]
This issue is so old, and I remember I fixed this a different way, so I'm closing it.
