### ISSUE TITLE
Use of deprecated Navigator component

### ISSUE THREAD

**Issue by andy-twosticks** [xotahal/react-native-material-ui#164]
I note that the demo app uses the deprecated Navigator component, and that the Dialog component, for example, appears to require a navigator in order to work.   I don't really want to use a component that has been deprecated!  

What other navigation components are supported?

**Comment by andy-twosticks** [comment]
Update: I've been trying to use [React Navigation](https://reactnavigation.org/docs/intro/).  It might simply be my ignorance (I'm a React Native beginner) but the Toolbar object does not seem to integrate; I get the React Navigation "toolbar" above it, which is obviously not right.

Again, this could be something that a more experienced React Native coder could fix. I don't know.

**Comment by cepm-nate** [comment]
@andy-twosticks any further progross? I'm running into the same thing (both toolbars), and would love an official answer on "How to use React Navigation with React Native Material UI".

**Comment by xotahal** [comment]
This library is not about navigation. It's only UI. It's up to you what navigation you are gonna use. Si the question is "How to use React Navigation with React Native app" and there is a plenty of articles about that ...

**Comment by aburai** [comment]
@cepm-nate do you mean something like this?

```javascript
static navigationOptions = ({ navigation }) => ({
    header: <Toolbar
      leftElement="arrow-back"
      onLeftElementPress={() => navigation.goBack()}
      centerElement="Title"
      rightElement="menu"
      onRightElementPress={() => navigation.navigate('DrawerOpen')}
    />
  })
```

**Comment by cepm-nate** [comment]
Thanks aburai, that just might do the trick! I was not aware you could combine the navigationOptions and a custom component.

**Comment by aircatcher** [comment]
@xotahal It's better to update your documentation and demo app to react-navigation anyway, so it's not misleading the beginners

**Comment by ayushyamitabh** [comment]
@aircatcher we're working towards a documentation website - sorry for the delay. This particular issue wasn't really about this library and dealt more with react-navigation -- using 2 libraries together is something the developer should be able to figure out. With that said, we will try to add relevant examples to the documentation.
