### ISSUE TITLE
Declare lodash as peer dependecy or document explicit requirement.

### ISSUE THREAD

**Issue by jjzazuet** [xotahal/react-native-material-ui#18]
Hi. I just found out that I needed to declare `lodash` v4 in my top level `package.json`. Otherwise, `getTheme.js` will fail at runtime. Thanks!

**Comment by xotahal** [comment]
Doesn't make any sense to have lodash there. I will us ES6 instead lodash's merge.

Thanks again @jjzazuet  ;)

**Comment by xotahal** [comment]
Uff, I added lodash as peer dependency for now - there is a deep merge and it's not so easy in ES

**Comment by xotahal** [comment]
Use this https://www.npmjs.com/package/lodash.merge

**Comment by xotahal** [comment]
In [v1.2.5](https://github.com/xotahal/react-native-material-ui/releases/tag/v1.2.5) is lodash.merge. I tried with react-native init project and it works fine
