### ISSUE TITLE
(Request) Please update version

### ISSUE THREAD

**Issue by delia-m** [xotahal/react-native-material-ui#184]
Hi all, 
I have seen awesome PRs are merged includes #171 and #178 
But v1.12.0 still makes warning, it doesn't seem have above changes.
Please update tag with version! 
Thanks!

**Comment by kenma9123** [comment]
or `yarn add react-native-material-ui@https://github.com/xotahal/react-native-material-ui` for the time being. But I really hope there's a new npm version.

**Comment by delia-m** [comment]
@kenma9123 I already have done with that but I also hope same as you. I'm gonna close this and looking forward for new npm :)
