### ISSUE TITLE
How to use the library with expo ?

### ISSUE THREAD

**Issue by a-eid** [xotahal/react-native-material-ui#193]
`undefined is not an object (evaluating'_context$uiTheme.button') ....`

also is a good idea to use `expo` for an app that is going for production soon ?? 

thank you

**Comment by tiaanduplessis** [comment]
I'm currently using it with `expo`, just installing `npm i -s react-native-material-ui` should work. Make sure to wrap your application in a theme provider component e.g:

```jsx
import { ThemeProvider } from 'react-native-material-ui'
const App = () => (
        <ThemeProvider uiTheme={{}}>
          <Stack />
        </ThemeProvider>
)
```

What concerns do you have with using expo for a production app?

**Comment by nkov** [comment]
I'm having the same issue with this library on Expo. I have my application wrapped in `<ThemeProvider>` and the only child is a `<StackNavigator>` component from `react-navigation`.  The context doesn't get passed down to any of the children.

**Comment by semiautomatix** [comment]
So can we confirm if this is working or not?

**Comment by rpkRED** [comment]
it's not working.

**Comment by wodka** [comment]
it is working :)
