### ISSUE TITLE
Need Last Commit

### ISSUE THREAD

**Issue by mehdizadeh93** [xotahal/react-native-material-ui#204]
Hi,
I need  the last commit `#5ae47c8`, Please create a New Releases.

**Comment by Hunsu** [comment]
As a workaround you can always install the version on GitHub.

**Comment by RobertSheaO** [comment]
@mehdizadeh93 for reference, you'd add it to your package.json like so

```
"react-native-material-ui": "git+https://github.com/xotahal/react-native-material-ui#5ae47c8",
```

You could omit the commit hash at the end if you just want the latest from the master branch, which at the time of this writing, is the hash you've referenced.

**Comment by xotahal** [comment]
New version was released
