### ISSUE TITLE
undefined is not an object in react-native-material-ui

### ISSUE THREAD

**Issue by gitofrajeshdeveloper** [xotahal/react-native-material-ui#211]
Hi, I found an error while using this.

when I added **"import { COLOR, ThemeProvider } from 'react-native-material-ui';"** to my App.js file.. it throws undefined is not an **object(evaluating '_react2.PropTypes.oneOf')**

how can I get rid of this error????

here is the screenshot of an error.

![screenshot_20171011-163113](https://user-images.githubusercontent.com/20432151/31437224-2b423730-aea2-11e7-996e-5e4804f5015a.png)

**Comment by ebonventi** [comment]
I cloned and I executed the demo successfully, but when i add react-native-material-design in a new project, i got the same problem. Someone know how to resolve that?

**Comment by ebonventi** [comment]
The problem occurr because react-native-vector-icons is out of date. PropType was deprecated in react package, from now we need to import PropType from prop-types package.

**Comment by chenop** [comment]
Thanks @ebonventi - But can you please clarify what is the solution for this case?

**Comment by SanderVerkuil** [comment]
@chenop it appears that you need to upgrade the React Native Vector Icons module to a new version supporting the removed PropTypes from react

**Comment by patelbrinda** [comment]
Hi I am facing the same error . I have use this react version 
react-native-cli: 2.0.1
react-native: 0.55.3
can you guide me to solve issue

**Comment by xotahal** [comment]
I recently updated all dependencies - let us know if you still have a problem. https://github.com/xotahal/react-native-material-ui/releases/tag/1.30.0
