### ISSUE TITLE
Warning prop type: the prop 'searchable' is marked required in 'RightElement', but it's value is 'null'

### ISSUE THREAD

**Issue by sunaryohadi** [xotahal/react-native-material-ui#215]
![screen shot 2017-10-18 at 19 34 42](https://user-images.githubusercontent.com/2224395/31718859-9e8282a6-b43b-11e7-9471-30eecfd7d654.png)

I am using "react-native": "0.48.4",

**Comment by adrianicv** [comment]
Update material ui to the last version. The warning will disappear

**Comment by sunaryohadi** [comment]
Thank you ...
The warning has gone
