### ISSUE TITLE
Ripple effect extends outwards if button is rounded

### ISSUE THREAD

**Issue by whimsicaldreamer** [xotahal/react-native-material-ui#219]
I have a button with rounded edges , on tap or click on it the ripple effect extends outwards making it look like square. How can we fix this?
![20171029_111635](https://user-images.githubusercontent.com/8104493/32141046-d0f8c0b6-bc9b-11e7-99db-7f7f2306107d.gif)

**Comment by xotahal** [comment]
Have a same problem. Unfortunately, I think there's only one think.

You have to do something like this:

```js
<RippleFeedback style={{ container: { width, height, borderRadius }} > ... </RippleFeedback>
```

I believe there is no way how could we know how the wrapper looks like .. if anyone has an idea .. tell me ;)

**Comment by whimsicaldreamer** [comment]
@xotahal The button element from react-native-elements works perfectly. You can take a look at it. ;)

**Comment by xotahal** [comment]
I took a look - briefly. And it seems they don't have a ripple effect in iOS. There is this code:

```js
  if (!Component && Platform.OS === 'ios') {
    Component = TouchableHighlight;
  }
  if (!Component && Platform.OS === 'android') {
    Component = TouchableNativeFeedback;
  }
```

Can you send me a code line where I can find the idea?

**Comment by whimsicaldreamer** [comment]
@xotahal I guess - https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L164
The above part should give you an idea. (Hopefully)

**Comment by whimsicaldreamer** [comment]
Btw I have another issue (#229) opened, which is currently my primary issue. Can you take a look at it? (I will remove this comment once you are notified)
