### ISSUE TITLE
ListItem - on*ElementPress not working

### ISSUE THREAD

**Issue by harmon25** [xotahal/react-native-material-ui#222]
Am using the react-native-material-ui `ListItem` component in a `SectionList`

The onRight and onLeft ElementPress props used to work couple months back - but now they do not seem to fire - my left and right elements are icons.

Using the latest release 1.14.0 in an Expo app. 
Expo could be causing it - wondering if anyone else has noticed this behaviour?

Thanks!

**Comment by adrianicv** [comment]
Fixed in PR #209, available in master but not yet released.
