### ISSUE TITLE
Dialog onActionPress not working

### ISSUE THREAD

**Issue by tiongshunooi** [xotahal/react-native-material-ui#226]

**Comment by Izitable** [comment]
Hey, I don't know which versions you are using but I have onActionPress working with:
 react-native: 0.45
 material-ui: 1.12

I leave some sample code

`return (
      <View>
        <Dialog.Title>
          <Text>Confirmation</Text>
        </Dialog.Title>
        <Dialog.Content />
        <Dialog.Actions>
          <DialogDefaultActions actions={["Yes", "No"]} onActionPress={action => this.handleDialogAction(action)} />
        </Dialog.Actions>
      </View>
    );`

`handleDialogAction = action => {
    console.log(action);
  };
`

And on debugger I get:

![image](https://user-images.githubusercontent.com/9057410/32889107-6ba162ac-cac1-11e7-9e98-69d3e9be037c.png)

**Comment by icflorescu** [comment]
I can also confirm this bug.

I have tested on:
`react-native: 0.50.4`
`react-native-material-ui: 1.14.0`

The `onActionPress` handler **is not called**.

**Comment by jichu4n** [comment]
Had the same issue with `react-native-material-ui@1.14.0`. Upgrading to `react-native-material-ui@1.18.0` seems to have fixed the issue for me.

**Comment by xotahal** [comment]
Cool. Closing this .. thanks @jichu4n
