### ISSUE TITLE
ListItem height not definable via theme style

### ISSUE THREAD

**Issue by lil5** [xotahal/react-native-material-ui#227]
Without the avialibilty of using the prop `numberOfLines='dynamic'`
> like in Drawer
> https://github.com/xotahal/react-native-material-ui/blob/3d33522806fe6dc6008658a50b4259a94224841b/src/Drawer/Section.react.js#L92-L99

you can't edit the height.

source of issue:
https://github.com/xotahal/react-native-material-ui/blob/b2a7855e21526e076cbdf356d2e19104d4a4cc05/src/ListItem/ListItem.react.js#L111-L132

**Comment by SanderVerkuil** [comment]
I think that this project tries to implement the material design guidelines. The material design guidelines' spec states that for a single line list item the height must be 48. For dense list items it must be 40.

If this is desired, I'd imagine setting a prop in the container for the height.
