### ISSUE TITLE
Custom animation on Toolbar doesnt work

### ISSUE THREAD

**Issue by whimsicaldreamer** [xotahal/react-native-material-ui#229]
I am trying to change elevation of toolbar on scroll. Basically I need the toolbar to have an elevation of 0 and on scroll I need it to have 7. I am using ANIMATED API for the animation but I get a failed prop-type warning stating .
![screenshot_1511170475_crop](https://user-images.githubusercontent.com/8104493/33074692-21e485b0-ceed-11e7-8ec6-83fc3d679499.png)

**I am using the following code:**  

```
state = {
        scrollY: new Animated.Value(0)
    };
```

```
render() {
        const elevate = this.state.scrollY.interpolate({
            inputRange: [0, 1],
            outputRange: [0, 7],
            extrapolate: 'clamp'
        });
 
        console.log(elevate);
        return (
            <ThemeProvider uiTheme={uiTheme}>
                <View style={styles.contentWrapper}>
                    <CustomStatusBar themeColor={uiTheme.palette.primaryColor} elevation={0}/>
                    <View>
                        <Toolbar
                            leftElement="menu"
                            centerElement="Aloha"
                            searchable={{
                                autoFocus: true,
                                placeholder: 'Search your chats',
                            }}
                            onLeftElementPress={() => this.props.navigation.navigate('DrawerOpen')}
                            style={{container: {elevation: elevate}}}
                        />
                    </View>
```

And am animating it `onScroll`:
```
onScroll={Animated.event(
    [{nativeEvent: {contentOffset: {y: this.state.scrollY}}}]
)}
```

**cc:** @xotahal @iRoachie 

Guys really need some help desparately.

**Comment by whimsicaldreamer** [comment]
@xotahal any highlights on this one?

**Comment by xotahal** [comment]
It's enough to do sth like this I think:
```js
onScroll() {
   this.setState({ isScrolled: offset > 0 })
}

render() {
   <Toolbar
          style={{ container: { ...(this.state.isScrolled ? getPlatformElevation(7) : {}) }}
   </Toolbar>
}
```

You don't need Animated.View

**Comment by whimsicaldreamer** [comment]
@xotahal  I tried something like this but the elevation occurs only after the scroll stops.

**Comment by xotahal** [comment]
It has to work. If the _onScroll is called, the toolbar has to be re-rendered immediately after state is changed ... Did you try debug this? Is a Toolbar's render method executed?

**Comment by whimsicaldreamer** [comment]
I tried debugging and even posting my issue in SO but with no avail. Whenever the scroll stops the elevation change occurs only then as a result the change of elevation is sudden.

**Comment by whimsicaldreamer** [comment]
@xotahal is it possible to pass animated values to the toolbar as the solutions are not working. Any pointers?

**Comment by xotahal** [comment]
let me try this .. i'll come back to you ..

**Comment by whimsicaldreamer** [comment]
@xotahal Ok will be waiting as I am stuck with it for many days 😞

**Comment by xotahal** [comment]
![elevation](https://user-images.githubusercontent.com/3531955/33761112-4b54043e-dc08-11e7-8e39-e3fca6d0e1cb.gif)

**Comment by xotahal** [comment]
worked for me .. i put there elevation 16 to be sure you see the change .. here's the relevant code ..

```js
    constructor(props) {
        super(props);

        this.state = { elevation: 0 };
    }
    onScroll = (e) => {
        const { contentOffset } = e.nativeEvent;

        if (contentOffset.y > 0) {
            this.setState({ elevation: 16 });
        } else {
            this.setState({ elevation: 0 });
        }
    }
    render() {
        return (
                <Toolbar
                    style={{ container: getPlatformElevation(this.state.elevation) }}
                />
```

**Comment by whimsicaldreamer** [comment]
@xotahal I am getting `ReferenceError: Can't find variable: getPlatformElevation`.

**Comment by iRoachie** [comment]
@whimsicaldreamer you need to import `getPlatformElevation` from 'react-native-material-ui/styles/getPlatformElevation'

**Comment by whimsicaldreamer** [comment]
@iRoachie I tried `import getPlatformElevation from 'react-native-material-ui/styles/getPlatformElevation';` but I get warning in my IDE stating module is not installed.

**Comment by iRoachie** [comment]
My bad think that should be `react-native-material-ui/src/styles/getPlatformElevation`

**Comment by whimsicaldreamer** [comment]
@iRoachie I am still getting the warning that module is not installed but by today I will let you know whether the overall solution worked for me.

cc @xotahal

**Comment by whimsicaldreamer** [comment]
@xotahal @iRoachie The changes in elevation are still not smooth and not getting close to what @xotahal showed in the gif.

Mine are here:
![20171208_170015](https://user-images.githubusercontent.com/8104493/33764262-b4010302-dc39-11e7-8ec4-73d3ba66b640.gif)
![20171208_170121](https://user-images.githubusercontent.com/8104493/33764263-b6c8e794-dc39-11e7-9ce0-ffa39cdac9cd.gif)

**Comment by xotahal** [comment]
What about this?

```js
    onScroll = (e) => {
        const { contentOffset } = e.nativeEvent;

        if (contentOffset.y <= 0) {
            this.setState({ elevation: 0 });
        } else if (contentOffset.y < 4) {
            this.setState({ elevation: Math.round(contentOffset.y) });
        } else {
            this.setState({ elevation: 4 });
        }
    }
```

**Comment by whimsicaldreamer** [comment]
@xotahal same issue 😞

**Comment by xotahal** [comment]
How so? :) share with us your code ...

**Comment by whimsicaldreamer** [comment]
@xotahal you can have it here: https://pastebin.com/bNhY2jp5

**Comment by xotahal** [comment]
Could you provide a minimum of code that doesn't work for you? Remove those styles, ListItems, Buttons, etc. ... Remove as much as possible ...

And second thing ... Try it with bigger elevation than 4 ... try it with 48 for example ... just to see "the animation"

**Comment by whimsicaldreamer** [comment]
I need the list items to make the page scroll right? I can remove the buttons and give a bigger elevation value at most. Will it be alright?

**Comment by xotahal** [comment]
just share the minimum amount of code to recreate your problem

**Comment by whimsicaldreamer** [comment]
In that case, I guess what above I have shared is the bare minimum.

**Comment by xotahal** [comment]
Did you try this code on your device? I just need sth what I can copy and paste into my app and run it :) .. I need to recreate your problem ... It would be perfect if I have exactly same code like you have, otherwise, I will keep telling you it works for me .. And you will keep telling me it doesn't work .. :)

**Comment by whimsicaldreamer** [comment]
Yes the gifs I posted are from my actual device (Moto G4). I understand what you mean, you can take a look at the paste I sent you last, but you need to fill it with list of your own.

**Comment by xotahal** [comment]
If you want me to help you .. fill it please with simple <Text> components .. remove all styles .. remove everything that you don't need to recreate this problem ... 

You don't need this - <View style={styles.contentWrapper}> and this <View style={styles.chatListContainer}> and this <View>

**Comment by whimsicaldreamer** [comment]
I definitely want some help, so I was stripping it down and then I ran again, now it just like your gif. Any ideas? (I am sending posting the stripped down code in a moment)
![20171208_192528](https://user-images.githubusercontent.com/8104493/33768877-db156e6a-dc4d-11e7-8316-4614bae09f65.gif)

**Comment by whimsicaldreamer** [comment]
@xotahal here it is - https://pastebin.com/i97wMvvf
Hopefully that will run.

**Comment by xotahal** [comment]
this is what you want

```js
    onScroll = (e) => {
        const { contentOffset } = e.nativeEvent;

        if (contentOffset.y <= 0) {
            this.setState({ elevation: 0 });
        } else if (contentOffset.y < 4) {
            this.setState({ elevation: Math.round(contentOffset.y) });
        } else {
            this.setState({ elevation: 4 });
        }
    }
```

I don't see it in that code ..

**Comment by whimsicaldreamer** [comment]
Both of them works perfectly only if the page is stripped down.
```
onScroll = (e) => {
        const { contentOffset } = e.nativeEvent;

        if (contentOffset.y <= 0) {
            this.setState({ elevation: 0 });
        } else if (contentOffset.y < 4) {
            this.setState({ elevation: Math.round(contentOffset.y) });
        } else {
            this.setState({ elevation: 4 });
        }
    }
```
The above does the elevation gradually giving it a nice effect and the one in the paste also does the elevation while scrolling instead of my initial problem that the elevation occured only after scrolling stops.

**Comment by xotahal** [comment]
I have no idea where is your problem man. If this code works it's not a problem with react-native-material-ui.

**Comment by whimsicaldreamer** [comment]
I too don't know whats wrong with it. Only stripped down version works else, the elevation happens only when the scroll stops. 😞

**Comment by whimsicaldreamer** [comment]
@xotahal probably the issue is somewhere in the list item when I add custom components to the left, right and center elements. Need to find out more and will post here.

**Comment by whimsicaldreamer** [comment]
@xotahal it seems the issue arises when I add custom components `leftElement` and `centerElement` prop instead of strings. Is it a problem with the custom components am adding? Any thoughts?
