### ISSUE TITLE
List Item - divider is hidden

### ISSUE THREAD

**Issue by serus22** [xotahal/react-native-material-ui#233]
Hello I have found bug maybe ? 
please check if you have same result but i tested it in 2 separate projects:

So if I have flatlist, with more than 2 items, i want to display divider between list items
but i see divider only sometimes, it looks like its hidden behid next element
- render list:
`<FlatList data={items}
                    renderItem={(it: {item:MenuItem, index: number}) => <ListItem
            divider={true}
            onPress={() => {}}
            style={{container: styles.menuItem}}
            leftElement={it.item.icon}
            centerElement={{primaryText: it.item.label}} />} />`
- items: 
`const items: Array<MenuItem> = [
  {
    key: 'key1',
    to: '/user/roomDetail',
    label: 'Detail',
    icon: 'home'
  },
  ....
];`

solution: 
`const styles = StyleSheet.create({
  menuItem: {
    backgroundColor: 'transparent',
    marginTop: 2
  }
});`

![screenshot_20171130-150819](https://user-images.githubusercontent.com/5665925/33434814-baf46da2-d5e0-11e7-9c95-592d22175897.png)

**Comment by serus22** [comment]
note: if i removed backgroundColor: 'transparent' i see dividers after 1st and 3rd element, and if I put transparent background, i see divider only after 2nd item

**Comment by xotahal** [comment]
Hey man :)

from documentation:
See - https://facebook.github.io/react-native/docs/stylesheet.html#hairlinewidth

Important: A line with hairline width may not be visible if your simulator is downscaled.

**Comment by serus22** [comment]
that screen was captured  on LG nexus 5x, i will provide more testing and will see

**Comment by xotahal** [comment]
Ok. Feel free to open it again if you find out sth more
