### ISSUE TITLE
How to add some top padding to the Drawer.Header?

### ISSUE THREAD

**Issue by FezVrasta** [xotahal/react-native-material-ui#235]
I'm trying to add some top padding to avoid the content to get covered by the status bar, but if I simply add a `paddingTop` the background image will not fit and the footer will get cut.

I spent some time playing with the possible style customization but I can't get it to properly work. Ideas?

![image](https://user-images.githubusercontent.com/5382443/33486635-1a1fc518-d6ab-11e7-9cc4-c4e4ab016f61.png)

**Comment by FezVrasta** [comment]
Ok nevermind, I have to set the `contentContainer.height` to `150 + Constants.statusBarHeight`, and add some `paddingTop` to the `Drawer.Header.Account` `avatarsContainer`.

**Comment by natterstefan** [comment]
@FezVrasta Can you share an example how you changed the image? I have some issues to change it, and also the font styling (eg. color) of the footer. :) Thank you.

```jsx
<Drawer.Header.Account
    avatar={<Avatar icon='person' iconSize={45} />}
    footer={{
        dense: true,
        centerElement: {
            primaryText: 'TEST TEXT'  // how can i style this text?
        }
    }}
/>
```

**Comment by rheng001** [comment]
@natterstefan Hey, have you figured out how to change the color of the footer? I'm having the same problems. Thanks

**Comment by rheng001** [comment]
@natterstefan I have solved it, here was my solution. 

```const uiTheme = {
    palette: {
        primaryColor: '#003066',
        accentColor: COLOR.pink500
      },
    toolbar: {
        container: {
            height: 70,
            paddingTop: 20,
          },
      },
      
      listItem: {
        primaryText: {
            color: '#fff',
        },
        secondaryText: {
            color: '#fff'
        }
      }
  };
```
You have to edit your uiTheme style and change the color in the listItem prop. You pass the uiTheme as follows

```
<ThemeProvider uiTheme={uiTheme}>
...
...
```
