### ISSUE TITLE
Unable to resolve module lodash/mege in styles/getTheme.js

### ISSUE THREAD

**Issue by mikaoelitiana** [xotahal/react-native-material-ui#24]
I am trying to use react-native-material-ui in a new react-native project build with [ignite](https://github.com/infinitered/ignite) but I get the following error: 
<img width="375" alt="capture d ecran 2016-09-28 a 11 13 20" src="https://cloud.githubusercontent.com/assets/674667/18905649/d014c51c-856c-11e6-9f7a-e02658ef5a97.png">
I checked the getTheme.js file and it tries to import 'lodash/merge' yet this is not in dependencies.  I also tried the solutions proposed below but none worked.

**Comment by xotahal** [comment]
I've just move lodash to peerDependencies in last version. Do you have a react-native-material-ui@1.2.4 ?

**Comment by xotahal** [comment]
In [v1.2.5](https://github.com/xotahal/react-native-material-ui/releases/tag/v1.2.5) should be everything ok. Let me know otherwise please :)
