### ISSUE TITLE
Touchables not working inside Card

### ISSUE THREAD

**Issue by ArneSaknussemm89** [xotahal/react-native-material-ui#248]
Since updating past v1.14.0, it looks like `pointerEvents="box-only"` is getting set on multiple components which prevents nested "touchables" from being clicked (TouchableHighlight, Button, etc etc).

I think that should be either set to "auto" or let a user pass that prop down (instead of forcing box-only which prevents any nested elements from being clicked).

I.e.

`<Card pointerEvents="box-only"></Card>`

**Comment by jeaye** [comment]
I'm also seeing this problem. Perhaps related to https://github.com/xotahal/react-native-material-ui/pull/239

**Comment by legomind** [comment]
This issue bit me too. my entire app design was with cards

**Comment by xotahal** [comment]
It should be fixed in latest release. Can you guys confirm that? I am closing this - feel free to open it again if it's not fixed ...

**Comment by jeaye** [comment]
Yeah, working for me. Thank you!

**Comment by legomind** [comment]
Works for me too. Thanks.
