### ISSUE TITLE
TypeError:udefined is not a function

### ISSUE THREAD

**Issue by ShaharLahav** [xotahal/react-native-material-ui#26]
After the installation when trying to first run the app i am getting this Error:

`TypeError: undefined is not a function (evaluating 'remoteModules.forEach')...`

**Comment by xotahal** [comment]
You try it with basic [awesome-project](https://facebook.github.io/react-native/docs/getting-started.html#testing-your-react-native-installation)? Or you have some bigger project?

Try to delete `node_modules` and install everything again.

**Comment by ShaharLahav** [comment]
this is my dependencies : 
`    "babel-preset-stage-0": "^6.16.0",`
   ` "react": "15.3.2",`
 `  "react-native": "^0.34.0",`
  ` "react-native-material-kit": "^0.3.2",`
   ` "react-native-material-ui": "^1.3.0",`
   ` "react-native-section-menu": "^0.1.0",`
   ` "react-native-sortable-listview": "0.0.8",`
 ` "react-native-vector-icons": "^2.0.3",`
  `  "react-timer-mixin": "^0.13.3"`

**Comment by xotahal** [comment]
Well, It's very hard to say where is the problem. I can try it with similar dependencies .. but don't know when I'll have a time for that

**Comment by AbdoulayeKarimTraore** [comment]
I'm having the same kind of error except that mine says undefined is not an object when trying to import ActionButton from react-native-material-ui in my code. I clone the demo app and tried to run it and I got the same error, any ideas?

**Comment by AbdoulayeKarimTraore** [comment]
I resolved the issue on the demo by including react-native-material-ui as a dependency and replacing all the occurences of '../react-native-material-ui" by 'react-native-material-ui", trying to resolve the issues with importing in my own project
