### ISSUE TITLE
ListItemProps : there does not exist any "onLeftElementPress()" prop.

### ISSUE THREAD

**Issue by YashGadle** [xotahal/react-native-material-ui#265]
In the documentation, the "onLeftElementPress" props, but it is not in the declaration file.
It is also being used in the demo app. Please help!

**Comment by aburai** [comment]
@YashGadle which declaration file do you mean? which version of react-native-material-ui? i see no problems in the latest version 1.19.0

**Comment by xotahal** [comment]
```js
    onLeftElementPressed = () => {
        const { onLeftElementPress, onPress, onPressValue } = this.props;

        if (onLeftElementPress) {
            onLeftElementPress(onPressValue);
        } else if (onPress) {
            onPress(onPressValue);
        }
    }
```

It's right there ...

**Comment by cantide5ga** [comment]
hi @YashGadle perhaps https://github.com/xotahal/react-native-material-ui/pull/151 made some improvements on this?  

I'm assuming you are referring to a Typescript definition.
