### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [xotahal/react-native-material-ui#267]
@xotahal : 
Hello, I wanted to congratulate you on the module.

I read your articles on medium:

part1: https://medium.com/react-native-motion/toolbar-animation-in-react-native-fe89c4f8e4cf

part2: https://medium.com/react-native-motion/toolbar-animation-in-react-native-2-2-f04ac45c7c11

I tried to redo everything, but it does not work, it gives me some errors, the style part is missing too.

I could ask you if you could publish somewhere the complete example of the Toolbar Animation, the one proposed in the article, the one you see in the gif.
![](https://cdn-images-1.medium.com/max/800/1*6qwTpnnQqFI_PyGwPrsxRQ.gif)

I thank you in advance.

**Comment by aburai** [comment]
@Angelk90 hi, have a look at the toolbar demo
https://github.com/xotahal/react-native-material-ui-demo-app/blob/master/src/Toolbars/index.js
the one with the searchable prop works this way

**Comment by xotahal** [comment]
@Angelk90 as @aburai said, it's in demo app ;)
