### ISSUE TITLE
drawerSectionActiveItem: --> Warning: Failed prop type: Invalid props.leftElement key `color` supplied to `ListItem`

### ISSUE THREAD

**Issue by sunaryohadi** [xotahal/react-native-material-ui#270]
Using RN > 0.51, there's a warning appears.

Warning: Failed prop type: Invalid props.leftElement key `color` supplied to `ListItem`.

My temporary handling to supress this warning is:

```
const uiTheme = {
	...
	drawerSectionActiveItem: {
		leftElement: { },  // remove warning, no color
	},
	...
};
```

**Comment by aburai** [comment]
duplicate -> https://github.com/xotahal/react-native-material-ui/issues/250
