### ISSUE TITLE
Changelog or use releases

### ISSUE THREAD

**Issue by iRoachie** [xotahal/react-native-material-ui#272]
Hey! Been using and recommending your lib for over a year now. 

One peeve I have is that there's no changelog or no release notes. So when I upgrade, I have no idea what was changed/fixed. Just requesting that you either introduce a changelog.md or use releases notes feature with your tags. Example with tags/release notes [here](https://github.com/react-native-training/react-native-elements/releases).

**Comment by xotahal** [comment]
Hey :) I was doing them and I stopped doing them. I understand. Will try to do them again ;) thx man
