### ISSUE TITLE
Undefined error when using radio button

### ISSUE THREAD

**Issue by fithaN** [xotahal/react-native-material-ui#276]
Hi ,
I am getting undefined error when using radio button the way described in read me.

<img width="291" alt="screen shot 2018-01-23 at 8 22 44 pm" src="https://user-images.githubusercontent.com/33620488/35267719-4f144754-007b-11e8-861d-5de2d76eb285.png">

**Comment by xotahal** [comment]
it seems you didn't provide ThemeProvider ... https://github.com/xotahal/react-native-material-ui#usage
