### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'context.uiTheme.actionButton')

### ISSUE THREAD

**Issue by dottnit** [xotahal/react-native-material-ui#296]
(https://user-images.githubusercontent.com/22549080/36246469-fac1907a-1255-11e8-8a74-72411d190780.jpg)

**Comment by hjbramos** [comment]
Same here! 

```
// imports here...

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View>
        <ActionButton /> // default with icon (default icon is +)
        <ActionButton icon="done" /> // with done icon
      </View>
    );
  }
}

// propsTypes here...
```


 "prop-types": "^15.6.0",
  "react": "16.2.0",
  "react-native": "0.53.0",
  "react-native-material-ui": "^1.19.0",
  "react-native-vector-icons": "^4.5.0"

**Comment by dottnit** [comment]
@hjbramos I've resolved it. It actually works when you nest it within ThemeProvider like this.
`<ThemeProvider uiTheme={uiTheme}> 
//your code here
</ThemeProvider>`


P.S. : If you can figure out how to use custom styles for button, drop a comment. Thanks

**Comment by hjbramos** [comment]
@dottnit Glad you got it. I've nested it within ThemeProvider but my app always crashes. Thanks. 
To be honest, I started using react-native-material-ui today. I haven't used custom styles yet but in the readme.md it says that we can override like this: <Button style={{ container: { backgroundColor: 'blue' }}} />

**Comment by dottnit** [comment]
I'll try those styles out.
Try to put up things afresh. Make sure you've included all necessary packages. If possible, please share error screens, I'll help amap.

**Comment by hjbramos** [comment]
Works fine!  I can close now! Thanks.

```
type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <ThemeProvider uiTheme={uiTheme}>
        <View style={styles.container}>
          <ActionButton />
        </View>
      </ThemeProvider>
    );
  }
}
```
