### ISSUE TITLE
Drawer.Section throws a propType warning if any items have active === true

### ISSUE THREAD

**Issue by thomasw** [xotahal/react-native-material-ui#298]
Using version 1.19.0

> Warning: Failed prop type: Invalid props.leftElement key `color` supplied to `ListItem`.
> Bad object: {
>    "color": "#008089"
> }
> ...

This is reproducible with the following drawer implementation:

```javascript
import React, { PureComponent } from 'react'
import { Drawer } from 'react-native-material-ui'

export default class MyDrawer extends PureComponent {
  render() {
    const navItems = [
      {
        icon: 'timeline',
        value: 'Foo',
        onPress: ()=>{},
        // warning does not occur if active: false
        active: true
      }
    ]

    return (
      <Drawer>
        <Drawer.Section divider items={navItems} />
      </Drawer>
    )
  }
}
```

Note that the active item is still highlighted as one would expect it to be. This issue was introduced sometime after version 1.14.0.

I will try to dig into the cause of this a bit more Monday morning.

**Comment by artur99** [comment]
#299

**Comment by artur99** [comment]
It's a duplicate with #250 and #270 I think. I've found @aburai 's solution in #250 to be the best one, and made a pull request #299. Hope that's fine.

**Comment by thomasw** [comment]
Thanks for pointing me to the correct place and my apologies about the extra noise.
