### ISSUE TITLE
failed to build dependency graph

### ISSUE THREAD

**Issue by AbdoulayeKarimTraore** [xotahal/react-native-material-ui#30]
I have an error after having installed the module. When building the react-native app, the packager throws a naming collision error saying that there is a duplicate module. This is due to the fact that this module has react-native as a dependency, deleting the react-native folder in the node_modules of this module is a  workaround but my question is, why do you need react-native as a dependency of this module, and by that I mean wouldn't be better to have it as a devDevendecy? Using npm 3.10.0, react-native 0.30.0, react-native-cli 1.0.0
![2016-10-10_23h46_03](https://cloud.githubusercontent.com/assets/15995390/19252237/0d601cba-8f44-11e6-9c54-cf3872dd0eb0.png)

**Comment by xotahal** [comment]
Hey @AbdoulayeKarimTraore, 

you're right, we don't need to have react native as dependency. Sorry for that :/ Fixed in https://github.com/xotahal/react-native-material-ui/releases/tag/v1.3.2
