### ISSUE TITLE
How would I set the text on the Toolbar's "Searchable" element?

### ISSUE THREAD

**Issue by LaurentLousky** [xotahal/react-native-material-ui#304]
I'm trying to change the TextInput's text value on a button press, but I don't know how to access it from this component. It seems like you can only read the text from the onChangeText method, but there's no way to set it.

Thanks!

**Comment by nclong87** [comment]
Hey, have you found any solution for this?

**Comment by LaurentLousky** [comment]
I forked the repo and made the changes necessary. I never submitted a PR however. 

You can look at the 2 most recent commits on here to see how i did it: 
https://github.com/LaurentLousky/react-native-material-ui/commits/master

**Comment by nclong87** [comment]
Thank you 👍
