### ISSUE TITLE
Possible to apply button: upperCase to uiTheme

### ISSUE THREAD

**Issue by liamheneghan** [xotahal/react-native-material-ui#308]
**Expected:**
Applying `upperCase: false` in the `uiTheme` to cause all buttons in the components to not have their text converted to uppercase.

**Actual:**
Text in buttons remained uppercase.

I've been using to Demo app to try this out but it does not work. I'm fairly new to RN and JS in general but after looking at the source for Button it looks like `upperCase` is not pulled out of the context.uiTheme and instead is only through props.

**Use case:**
I'd like uppercase buttons for Android and lowercase buttons for iOS.

Thanks for the great library!

```

const uiTheme = {
    palette: {
        primaryColor: COLOR.blue500,
        accentColor: COLOR.pink500,
    },
    button: {
        upperCase: false,
    },
};
```

**Comment by riteshmalav** [comment]
by default the material design convention follows the button text in upper case i dont understand why you want to change the case of text in button.

**Comment by liamheneghan** [comment]
I'm aware of the design convention. There is also the facility to do this via the props of the Button <Button upperCase={false}/> so I don't believe the library owner wants to prevent you from doing this.

I'm asking if it is possible to this globally as part of the uiTheme.

**Comment by ayushyamitabh** [comment]
@liamheneghan Not sure if you're still looking for a way - perhaps editing the default prop values? Since you're sure that all buttons won't be all uppercase. Look at the [source file line 65](https://github.com/xotahal/react-native-material-ui/blob/master/src/Button/Button.react.js) - change that to false in your local file and you're good to go.
