### ISSUE TITLE
[Android only] Searchable Toolbar is Slow even with Dev Mode off 

### ISSUE THREAD

**Issue by AndrePech** [xotahal/react-native-material-ui#309]
Hi guys, i am experiencing a slow down when opening the search bar on Android. IOS runs fine even in the simulator. 

It takes around a second to start the animation after clicking the search icon, then the animation lags a little bit. When closing the same thing happens, but in the end the whole Toolbar flashes and returns to its normal state.

My screen has basically a Flatlist and the Toolbar.
I am using React Native Navigation and passing null to the header on the navigationOptions. (Otherwise I would have 2 Toolbar on the same screen);

I am not using Redux.

Is there a way to disable the show/hide animations?

My Render function:

``` javascript
<ThemeProvider uiTheme={uiTheme}>
                <View style={{ flex: 1 }}>
                    <Toolbar
                        leftElement="arrow-back"
                        centerElement="Pedidos de Compra"
                        onLeftElementPress={() => {
                            this.props.navigation.goBack();
                        }}
                        searchable={{
                            autoFocus: true,
                            placeholder: 'Search',
                            onChangeText: (text) => {
                                this.setState({ aprovacoesLista: this.search(text) });
                            },
                            onSearchClosed:()=>{
                                this.setState({aprovacoesLista:this.state.aprovacoes});
                            }
                        }}
                    />
                    {this.showListOrLoading()}
                </View>
            </ThemeProvider>
```

**Comment by riteshmalav** [comment]
i dont think there shall be any problem with the search bar but just to be sure can you please create a production variant of the application and test in that. you can run the prodcution variant of the application in emulator using folowing cmd react-native run-android --variant=release

**Comment by AndrePech** [comment]
@riteshmalav Thanks for the reply... I used a release apk and it did not help...
I honestly don't know what was causing the slow down, I implemented my own search bar and my problem has been solved.

**Comment by riteshmalav** [comment]
If you look at the demo project the search bar is preety fast and animation is also rendering good

**Comment by xotahal** [comment]
Don't think it is related to the search bar. Seems like a problem with the code around.
