### ISSUE TITLE
Adding logo to Toolbar

### ISSUE THREAD

**Issue by dineshmm23** [xotahal/react-native-material-ui#324]
```
<Toolbar
        leftElement="menu"
        centerElement="Searchable"
        logo="/src/image/mylogo.png" //Support image in the toolbar with or without the text
      />
```
**How about adding logo with text? It would be awesome right?**

[From Different source](https://stackoverflow.com/questions/36059749/react-native-android-how-to-set-the-logo-icon-in-toolbarandroid)
```
<ToolbarAndroid
  logo={require('./ic_launcher_icon.png')}
  navIcon={require('./ic_menu_black.png')}
  onIconClicked={() => this.drawer.openDrawer()}
  style={styles.toolbar}
  title={title}
/>
```
Please can u help me if there way i can add logo inside the toolbar.

**Comment by sunaryohadi** [comment]
You can do this anyway. You need custom your own component.

Here's he sample

	_logo () {
		return (
			<View style={{ flexDirection: 'row', alignItems: 'center', }}>
				<Image source={require('../../assets/images/logo.png')} 
					style={{ width: 24, height: 24, marginHorizontal: 5 }}
					resizeMode="contain" />
				<Text style={{ color: '#F03C29', fontWeight: 'bold', fontSize: 15, }}>MyLogo</Text>
			</View>
		)
	}

In your toolbar

	<Toolbar
		leftElement={ this._logo() } 
		centerElement=''
		rightElement="notifications"
		onRightElementPress={() => navigate('Notification')}
	/>

Hope it's help.
