### ISSUE TITLE
BottomNavigation.Action custom Icon

### ISSUE THREAD

**Issue by Unoken** [xotahal/react-native-material-ui#326]
How can i use a png file to icon prop in BottomNavigation.Action like this:

`<BottomNavigation.Action
                        key="Vomo"
                        icon="../img/icon_menu_vomo1.png"
                        label="Vomo"
                        onPress={() => this.setState({ active: 'Vomo' })}
                    />`

**Comment by janziemba** [comment]
@Unoken `<BottomNavigation.Action icon={<ImageOrWhateverYouWant />} />`
