### ISSUE TITLE
When clicking radio-button, the radio button does not select.

### ISSUE THREAD

**Issue by danielptm** [xotahal/react-native-material-ui#329]
I am building/deploying to xcode and running an app on the IOS simulator. When I use the Radiobutton component, it shows up fine, but it does not work to click the radio button and have it become selected. This is the same with the checkbox. Is this a bug, or what am I doing wrong?

**Comment by pohsiu** [comment]
u r wrong about not reading document ,

https://github.com/xotahal/react-native-material-ui/blob/master/docs/RadioButton.md
