### ISSUE TITLE
How to use Tolbar?

### ISSUE THREAD

**Issue by hoangvuanhdevelopervn** [xotahal/react-native-material-ui#335]
How to use toolbar?  I follow this [https://github.com/xotahal/react-native-material-ui/blob/master/docs/Toolbar.md]() but it's not working. This is my code and it's error: **TypeError: undefined is not an object(evaluating 'context.uiTheme.toolbar)**

```
import { Toolbar } from 'react-native-material-ui';
import React, { Component } from 'react'

export default class App extends Component {
    render() {
        return (
            <Toolbar
            leftElement="menu"
            centerElement="Searchable"
            searchable={{
                autoFocus: true,
                placeholder: 'Search',
            }}
            />
        )       
    }   
}

```

**Comment by hoangvuanhdevelopervn** [comment]
Some can give an example?

**Comment by janziemba** [comment]
So you have fixed it after reading the docs, closing https://github.com/xotahal/react-native-material-ui#usage
