### ISSUE TITLE
unable to change the properties of the theming object

### ISSUE THREAD

**Issue by hemraj-s** [xotahal/react-native-material-ui#344]
I am using this library along with react-native-navigation and have set the theming in the provider as follows:

`const myProvider = ({ store, children }) => (
  < Provider store = {store} >
   < ThemeProvider uiTheme = {userTheme} >
      {children}
    </ ThemeProvider >
  </ Provider >
);

export default myProvider;`

While I can see the theme object in the context; it doesnt seem to contain the values that I have set in the userTheme object. Is there anything that I am missing on. I also tried adding new properties and that too dont seem to be working.

**Comment by ayushyamitabh** [comment]
I am also working on a project using this along with react navigation.
Take a look at my implementation, it worked for me:
https://github.com/ayushyamitabh/PizzaOrderSystem/blob/Customer/app/App.js

**Comment by hemraj-s** [comment]
The difference between your implementation and mine is that I am using a different navigator i.e. react-native-navigation.

Not sure if it is because of that. Otherwise I have done the exact same thing.

**Comment by ayushyamitabh** [comment]
@hemraj-s have you defined your userTheme properly - could you post that please. If that's defined correctly - could you try making the `ThemeProvider` as the parent element or is there a particular reason you can't?

**Comment by hemraj-s** [comment]
@ayushyamitabh I have tried the code from sample as below 
`const uiTheme = {
    palette: {
        primaryColor: COLOR.green500,
    },
    toolbar: {
        container: {
            height: 50,
        },
    },
};`

So while I see the object in my component, I dont get to see the change that I make to it. For e.g. if I change the color from green to blue, then I dont see that change. Additionally I would like to add more keys to the object.

Will try and make the change that you have suggested (of making ThemeProvider as the parent) and revert back.

**Comment by xotahal** [comment]
Hey, the way how we are using context was changed in version 1.30. Now it will work corectly when you are changing the uiTheme dynamicaly. See the [savee.io app](https://savee.io)

![theme](https://user-images.githubusercontent.com/3531955/41945204-fe9da744-79ff-11e8-8520-074ad59bedc5.gif)
