### ISSUE TITLE
How to style footer in Drawer

### ISSUE THREAD

**Issue by rheng001** [xotahal/react-native-material-ui#348]
Hi,

I'm trying to style the footer in the drawer section, tried the following

> footer={{
                                    dense: true,
                                    centerElement: {
                                        primaryText: 'User',
                                        secondaryText: 'user@email.com',
                                    },
                                    style: {
                                        primaryText: {color: 'red'},
                                        secondaryText: {color: '#fff'}
                                    }
                                  }}

but the text color doesn't seem to change.

**Comment by ayushyamitabh** [comment]
@rheng001 Please refer to the Drawer [documentation here](https://github.com/xotahal/react-native-material-ui/blob/master/docs/Drawer.md#headeraccount-api).  `primaryText` and `secondaryText` don't seem to be the expected keys.

**Comment by rheng001** [comment]
@ayushyamitabh  Hmm nothing seems to be working, I see that the documentation says that the footer uses  ListItem.propTypes, and I went to that doc and the props are Text.propTypes.style. I've tried multiple keys but the color still doesnt change.

**Comment by ayushyamitabh** [comment]
@rheng001 Just to be sure - you're not using `Text.propTypes.style` as a key right? I think you might not completely understand how styling works with React-Native. Pardon me if my assumption is wrong.

It should look something like this - this is an incomplete example, modify it according to your need:
```jsx
<Drawer>
    <Drawer.Header>
        <Drawer.Header.Account
                footer={{
                    dense: true,
                    centerElement: {
                        primaryText: 'Reservio',
                        secondaryText: 'business@email.com',
                    },
                    rightElement: 'arrow-drop-down',
                }}
               style={{
                  accountContainer: {color:'white'}
               }}>
        </Drawer.Header.Account>
    </Drawer.Header>
</Drawer>
```
----
From the Documentation:
### HeaderAccount API
```jsx
const propTypes = {
    avatar: PropTypes.element,
    accounts: PropTypes.arrayOf(PropTypes.shape({
        avatar: PropTypes.element,
        onPress: PropTypes.func,
    })),
    footer: ListItem.propTypes,
    style: PropTypes.shape({
        container: View.propTypes.style,
        accountContainer: View.propTypes.style,
        topContainer: View.propTypes.style,
        avatarsContainer: View.propTypes.style,
        activeAvatarContainer: View.propTypes.style,
        inactiveAvatarContainer: View.propTypes.style,
    }),
};
```

**Comment by rheng001** [comment]
Right I understand, I'm just trying to specifically target the primaryText and secondaryText font color inside of the centerElement from inside the footer.

**Comment by ayushyamitabh** [comment]
@rheng001 Ah, I see the issue now - so sorry for the confusion. 
Not sure why you divided it into 2 objects for the footer, have you tried:
```jsx
footer={{
    primaryText: 'User Name',
    secondaryText: 'user@email',
    style: {{
       primaryText: {color : 'white'},
       secondaryText: {color : 'red')
    }}
}}
```

**Comment by rheng001** [comment]
I tried your way, but there was errors with that code. This is how my Drawer.Header is configured. Still cant get primary and secondary text to change. >_<

```ruby
<Drawer.Header
                                style={{
                                    contentContainer: {
                                        height: 150 + StatusBar.currentHeight
                                    }
                                }} 
                                image={<Image 
                                style={StyleSheet.absoluteFill}
                                source={{ uri: 'https://i.imgur.com/iYfuXFV.jpg' }} />}>

                                <Drawer.Header.Account                                
                                avatar={<Avatar 
                                    image={<Image 
                                        style={StyleSheet.absoluteFill}
                                        source={{ uri: 'https://i.imgur.com/Ax25IWf.gif' }} />} />}
                                
                                footer={{
                                    dense: true,
                                    centerElement: {
                                        primaryText: 'Richard Heng',
                                        secondaryText: 'rheng001@ucr.edu',
                                    },
                                    style: {
                                        primaryText: {color : 'white'},
                                        secondaryText: {color : 'red'}
                                     }
                                  }}
                            />
</Drawer.Header>
```

**Comment by rheng001** [comment]
I think I have found the solution, I had to edit my ThemeProvider uiTheme style as follows

```
const uiTheme = {
    palette: {
        primaryColor: '#003066',
        accentColor: COLOR.pink500
      },
    toolbar: {
        container: {
            height: 70,
            paddingTop: 20,
          },
      },
      
      listItem: {
        primaryText: {
            color: '#fff',
        },
        secondaryText: {
            color: '#fff'
        }
      }
  };
```

The problem is it effects all of the drawer listitems as follows

![err](https://user-images.githubusercontent.com/14899915/39655318-c390e0a2-4fad-11e8-8aad-bd21cbcde1de.png)

**Comment by ayushyamitabh** [comment]
@rheng001 I think if you missed a pair of `{}` for the style tag.
So it would look something like:
```jsx
footer={{
    style:{{
      primaryText: {}
    }}
}}
```
Or was that causing the error.

Either way, glad you figured a way around.

**Comment by brunoksato** [comment]
@rheng001 Is simple, follow solution

```const uiTheme = {
  drawerHeaderListItem: {
    primaryText: {
      color: 'white',
    },
    secondaryText: {
      color: 'white',
    }
  }
};```

**Comment by kirill-konshin** [comment]
Still it's impossible to pass style directly to `Drawer.Header.Account` footer.
