### ISSUE TITLE
__DEV__ is undefined in index.js

### ISSUE THREAD

**Issue by LadislavBohm** [xotahal/react-native-material-ui#36]
Hello,

problem with undefined __DEV__ variable in index.js appeared after I updated to version 1.3.2.

Problem seems to be when .babelrc was added in version 1.2.2 is there something I have to do when updating to 1.2.2+?

When I downgraded  back to 1.2.0 everything works fine. RN version is 0.35.

**Comment by jjzazuet** [comment]
@LadislavBohm  I think it's fixed in `1.3.2`. If it still happens, just delete the `.babelrc` file from the downloaded package. Cheers!

**Comment by xotahal** [comment]
@LadislavBohm Where exactly is the DEV variable? :)

**Comment by LadislavBohm** [comment]
Hmmm, I swear it was there when I updated to 1.3.2 in file index.js. However I cannot reproduce it when I start a new project, nor when I update it now.

So I'm sorry for probably false report, maybe it was some error during update/linking.
