### ISSUE TITLE
ThemeProvider is no longer exported

### ISSUE THREAD

**Issue by Tokimon** [xotahal/react-native-material-ui#375]
I have updated to your latest version (1.30.0 from 1.22.3) and there `ThemeProvider` is no longer exported. However it is still mentioned in the ReadMe. So how do I handle Themes in the newest version? and could you please update the ReadMe to reflect your changes?

Thank you in advance

### A bit of explanation
I include the `ThemeProvider` by doing:
```js
import { ThemeProvider } from 'react-native-material-ui';
```

Which is the same as your description:
```js
import { COLOR, ThemeProvider } from 'react-native-material-ui';
```

But `ThemeProvider ` is undefined. I looked at your `src/index.js` and `ThemeProvider` is not included/exported from it.

**Comment by osiellima** [comment]
I have the same problem.

**Comment by osiellima** [comment]
The change is described in breaking changes of the new version.

**Comment by Tokimon** [comment]
Ok got that.
But I think the README should be updated to reflect this. Right now it still explains the old way of doing it.

**Comment by xotahal** [comment]
I updated that a couple of days ago ... https://github.com/xotahal/react-native-material-ui/blob/master/docs/Usage.md#usage

Is it anywhere else?
