### ISSUE TITLE
Card don't have Media, Body and Action unlike example image

### ISSUE THREAD

**Issue by mikaoelitiana** [xotahal/react-native-material-ui#38]
The example image displayed on the README has a Card with 3 parts in the Welcome screen: 

![https://raw.githubusercontent.com/react-native-material-design/demo-app/master/resources/examples-1.jpg](https://raw.githubusercontent.com/react-native-material-design/demo-app/master/resources/examples-1.jpg)

Anyway, I can't get a similar render because Card components doesn't have these parts yet.

**Comment by meiraleal** [comment]
It's a lot of work to port material-ui. We should help :)

**Comment by sood03** [comment]
You can implement this card from [this material design repo](https://github.com/react-native-material-design/react-native-material-design)

**Comment by zhuber** [comment]
Until this is implemented, the screenshot should be removed from the Homepage of this repo. It's very misleading and I would argue that it's a core piece of functionality for the Card component.
