### ISSUE TITLE
[Feature request][Toolbar] Change icon set for specific left/right element (not whole component)

### ISSUE THREAD

**Issue by kientux** [xotahal/react-native-material-ui#383]
With latest release, I know we can change icon set for a component. But it will be nice if we can use different iconset for each left or right element too 😬 Sometimes an iconset is not enough...

(I know I can use custom `<Icon />` component for that, but it will lose the ripple effect. If I want ripple effect I must wrap icon with some ripple-enabled button, but ehhh it's becoming complicated and maybe not synced with this library styles...)

**Comment by ahmedu007** [comment]
I think instead it would be better to pass a JSX element to the left and right prop. You can import whichever Icon set you want and just pass the component inside. That should work

**Comment by xotahal** [comment]
`<IconToggle />` has the ripple effect. You can use this ...
