### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ahmedu007** [xotahal/react-native-material-ui#388]
Hey, just wondering if there is a possibility to extract the Icon animation from the Toolbar to be a separate component? The Animation on the toolbar that spins the icon when search is activated and vice versa is really nice, and would be good to have to use it for standard drop downs or other icons.

**Comment by xotahal** [comment]
Would be maybe better to implement this effect to https://github.com/xotahal/react-native-motion? Somethink like:

```js
<Spin>
     <Icon />
</Spin>
```

**Comment by ahmedu007** [comment]
Yea that would work too I guess. With a rotation prop that takes the degree of movement. That would be awesome thanks. Shall I close this issue then?

**Comment by xotahal** [comment]
Yeah, post it over there, please...
