### ISSUE TITLE
ThemeProvider component is broken on React Native 0.57

### ISSUE THREAD

**Issue by nicolasconnault** [xotahal/react-native-material-ui#413]
It was working fine on 0.55, but after updating my code to 0.57, the component throws the following error:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by xotahal** [comment]
Why do you think it is caused by this library?

I am on RN 0.57.4 and all work ...

**Comment by bdelville** [comment]
This is throwing the same error as described, on Android:
`export default class App extends Component<Props> {
  render() {
    return (
      <ThemeProvider> <Text>Hello</Text> </ThemeProvider>
    );
  }
}`

This is working fine (after only this single change):
`export default class App extends Component<Props> {
  render() {
    return (
      <Text>Hello</Text>
    );
  }
}`

Error:
`E/ReactNativeJS: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `App`.
    
    This error is located at:
        in App (at renderApplication.js:34)
        in RCTView (at View.js:45)
        in RCTView (at View.js:45)
        in RootSiblingsWrapper (at AppContainer.js:112)
        in RCTView (at View.js:45)
        in AppContainer (at renderApplication.js:33)`
