### ISSUE TITLE
Icon Button

### ISSUE THREAD

**Issue by benkaiser** [xotahal/react-native-material-ui#414]
I'm looking to create buttons in my application that do not contain text (only an icon).

Could we either create a new component (<IconButton />?) or make the text parameter of button optional and make it so the button is square around the icon (rather than taking up an extra space when an empty string is passed)?

**Comment by thomasw** [comment]
https://github.com/xotahal/react-native-material-ui/blob/master/docs/IconToggle.md

**Comment by benkaiser** [comment]
Perfect
