### ISSUE TITLE
 change the color of the ActionButton button bar

### ISSUE THREAD

**Issue by joaodematejr** [xotahal/react-native-material-ui#432]
I can not change the bar as it can be seen in gif

[https://ibb.co/hD5vcQ8](https://ibb.co/hD5vcQ8)

```
                        <ActionButton
                            style={{ container: { elevation: 0, backgroundColor: '#047cc4' }, 
                            content: { backgroundColor: '#047cc4' } }}
                            actions={[{ icon: 'account-circle', label: 'Perfil' },
                            { icon: 'games', label: 'Quiz' },
                            { icon: 'local-grocery-store', label: 'Comprar' },
                            { icon: 'send', label: 'Transferir' },]}
                            icon="account-balance-wallet"
                            transition='toolbar'
                        />
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17418041/54681574-7e679b80-4aeb-11e9-8e01-cb9aee846566.gif)

**Comment by moiseshilario** [comment]
Hello @joaodematejr You should use `toolbarContainer` as specified [here](https://github.com/xotahal/react-native-material-ui/blob/master/src/ActionButton/ActionButton.react.js#L280)

`container` should be used for the button
`toolbarContainer` should be used for the bar

Hope it helps ;D

Like this:

```js
      <ActionButton
            style={{
              container: { backgroundColor: '#047cc4' },
              toolbarContainer: { elevation: 0, backgroundColor: '#047cc4' },
            }}
...
```
![image](https://user-images.githubusercontent.com/11222413/55183267-35a88600-516e-11e9-9816-2a37ea6ea249.png)

![image](https://user-images.githubusercontent.com/11222413/55183276-3c36fd80-516e-11e9-8e22-effe270831d2.png)

**Comment by joaodematejr** [comment]
Yes, thank you. Thank you very much.
