### ISSUE TITLE
BottomNavigation icon

### ISSUE THREAD

**Issue by whittlem** [xotahal/react-native-material-ui#445]
Should all these icons work?
https://material.io/tools/icons/?style=baseline

Very few icons actually load. Is there a list of available icons for react-native-material-ui?

**Comment by Kich-kichi** [comment]
@whittlem, Hello!

This components library use [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons).
So you can check all available icons there. 

With best regards,
Andrew Bash

**Comment by whittlem** [comment]
Thanks very much. That is really helpful and just what I was looking for. The most direct link to the icon list is here... https://oblador.github.io/react-native-vector-icons/
