### ISSUE TITLE
LeftElement in Toolbar can be only icon name.

### ISSUE THREAD

**Issue by pfulop** [xotahal/react-native-material-ui#45]
Hi,
Love your work btw. 
However I tried putting custom view into leftElement in Toolbar Props but got error. I inspected your code and found out that no matter what, left element will be rendered as a IconToogle and props I sent there will be used as icon name. Either it's bug in proptypes where you should check only if leftElement is a string, or missing implementation of rendering custom element set via props.

**Comment by xotahal** [comment]
Hi @pfulop, thank you ;)

Correct answer is:
> missing implementation of rendering custom element set via props.

You can try to make pull request if you want ;)

**Comment by pfulop** [comment]
Will do

**Comment by xotahal** [comment]
Fixed https://github.com/xotahal/react-native-material-ui/pull/46
