### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by kncerbero** [xotahal/react-native-material-ui#452]
I receive this warning from my react-native project:

componentWillReceiveProps is deprecated and will be removed in the next major version.
Use static getDerivedStateFromProps instead.

Please update the following components:
CenterElement, IconToggle, LeftElement, Toolbar.

**Comment by mbrucher** [comment]
Good point, as React will very soon get upgraded to its next major version.
Is the project still actively maintained (material-ui got updated to 4.0)? Or is there another similar project that took over?

**Comment by kncerbero** [comment]
> Good point, as React will very soon get upgraded to its next major version.
> Is the project still actively maintained (material-ui got updated to 4.0)? Or is there another similar project that took over?

never mind, i resolve my problem changing that hook for componentDidUpdate.
https://stackoverflow.com/a/51981144

**Comment by chenop** [comment]
@kncerbero those elements are comopnents inside the react-native-material-ui package.
Have you change the code inside the package? if so this should b re-opened so a fix will be made I think.

**Comment by Dinnu801** [comment]
@chenop this issue still persists. I tried adding toolbar as my header.

**Comment by chenop** [comment]
@Dinnu801 this package is not maintained for a long time now - I switched to react-native-elements
