### ISSUE TITLE
Customize badge background color

### ISSUE THREAD

**Issue by sood03** [xotahal/react-native-material-ui#48]
I could not find any option to change the badge background color. In the Badge class, it is defined to get the badge background color from palette.accentColor
In my case, I am keeping my badge on an icon which are on the toolbar. So the toolbar color and badge background color are picked both from the palette.accentColor.

Is there any option to change the badge background color?

**Comment by xotahal** [comment]
You can change any style of any component. Each component has a style prop. So for that Badge component you can define background color like this:

```<Badge style={{ container: { backgroundColor: 'yellow' } }} />```

**Comment by sood03** [comment]
My bad. I tried with the background color but wrote it outside the container.
This worked: <Badge text="9" style={{ container: {top: 2, right: -1, backgroundColor: "#ff0000"}  }} >

Thanks :)
