### ISSUE TITLE
LIstItem center element not clickable

### ISSUE THREAD

**Issue by mikaoelitiana** [xotahal/react-native-material-ui#49]
I am using a the Drawer and added items to it but I noticed that text part of the drawer content is not clickable, only the icon is. Is there a particular reason for that? I see in the ListItem code that only leftElement and rightElement have click events. 
I would love to have this event on the centerElement as well.

**Comment by xotahal** [comment]
There is [onListItemPressed](https://github.com/xotahal/react-native-material-ui/blob/master/src/ListItem/ListItem.react.js#L187) method that calls prop's `onPress` method. Is that what you need?

**Comment by mikaoelitiana** [comment]
I see. But strangely, when I set my Drawer like so, the text is not clickable, only the icon 

```
render () {
    let menuItems = [{ icon: 'settings', value: I18n.t('settings'), onPress: this.handlePressSettings }]
    if (Platform.OS === 'android') {
      menuItems.push({ icon: 'power-settings-new', value: I18n.t('quit'), onPress: this.handlePressQuit })
    }
    return (
      <Drawer>
        <Drawer.Section
          items={menuItems}
        />
      </Drawer>
    )
  }
```

**Comment by mikaoelitiana** [comment]
I think I see why it do so: 

```
onListItemPressed = () => {
        const { onPress, onPressValue } = this.props;

        if (onPress) {
            onPress(onPressValue);
        }
    };
```

yet [onPressValue](https://github.com/xotahal/react-native-material-ui/blob/master/src/ListItem/ListItem.react.js#L187) is not set

**Comment by mikaoelitiana** [comment]
Finally not sure
