### ISSUE TITLE
undefined is not an object upon import

### ISSUE THREAD

**Issue by vonovak** [xotahal/react-native-material-ui#5]
Hi! I wanted to try out your toolbar, but whenever I import something from your module, I'm getting `undefined is not an object` at create-icon-set.js line 46. I suppose it is due to the outdated dependencies when installing through npm. My Rn version is 0.26.2

Would be nice if you pushed your components to the original repo, so that the community could benefit from them..
thanks!

edit: installing from repo doesn't work for me, either :/
btw. the dependecies badge you are using (https://david-dm.org/react-native-material-design/react-native-material-design.svg) is for a different project.
edit2 not sure what the problem was, but when I clonned your repo locally and updated the icons dependency it worked. nice job indeed

**Comment by jurosh** [comment]
Same issue - just installed brand latest stable react native "react-native": "0.29.0"
So this issue is there - will try to clone as you suggested but it's not like solution to existing issue...

**Comment by xotahal** [comment]
There is probably issue with react-native 0.26 where were some breaking changes. I fixed it in master branch but didn't upload to npm yet.
