### ISSUE TITLE
Material Switch Button

### ISSUE THREAD

**Issue by kenma9123** [xotahal/react-native-material-ui#79]
I know there's an existing `Switch` component from react native. But the default switch does not allow you to change the background color when turned on nor the thumb tints color. On iOS though it's possible via `onTintColor `, `thumbTintColor ` and `tintColor`.

**Comment by HofmannZ** [comment]
@kenma9123 I will need the material switch as well, so you will see a PR in the near future.

**Comment by xotahal** [comment]
Hey guys, there is already pull request in React Native .. so we should wait for it ;)

https://github.com/facebook/react-native/pull/11940
