### ISSUE TITLE
Info for react-native-material-ui

### ISSUE THREAD

**Issue by lawlessnut** [xotahal/react-native-material-ui#83]
Hi Guys,

i am new to react-native. i know reactjs and use extensively. Now react-native provide its own component like List, Buttons, View etc.. how they are different from what react-native-material-ui provide (this plugin) ? is there difference in terms of what lies behind code. I mean to say react-native-component ties to specific platform related components. Is there different where i want to use what this plugin provide and refuse to use react-native-components.

**Comment by Cleanshooter** [comment]
If you take some time to review the code in this library you'd find the answer to your question.  (TLDB)  This library is built on react native components like, List, Button, View and Text; it just styles them so they'll have a look and feel analogous to Google Material Design.  The difference is what you want your componenets to look like.  If you want "Native" look and feel don't use this library, if you want Material Design look and feel use this library.

**Comment by lawlessnut** [comment]
@Cleanshooter This answer my question. I'm starting my new project based on react-native. This is perfect suit for me.
