### ISSUE TITLE
Button Diasbled issues...

### ISSUE THREAD

**Issue by Cleanshooter** [xotahal/react-native-material-ui#84]
There are a slew of things that needed updating with the Button component so it will function properly when the disabled condition is true.  Currently if you set it to disabled, raised and primary simultaneously it will look like an active button but won't allow the user to click it.  So it's half right.

A disabled button should really display as such whenever the disabled property is true. 

Working on a PR right now...

**Comment by xotahal** [comment]
Super ;) Thanks @Cleanshooter so far

**Comment by xotahal** [comment]
Fixed in 1.9.0
