### ISSUE TITLE
How to render the FAB?

### ISSUE THREAD

**Issue by kenma9123** [xotahal/react-native-material-ui#9]
First I would like to thank you for continuing this project from @Ehesp that was also forked from @binggg. I can see from your demo that you have a FAB working on the view, how'd you use that. I was looking for a documentation but just like the rest I think it has to be improve. But again thank you! :+1:

**Comment by xotahal** [comment]
Agree, it should be improved. I use this - https://github.com/mastermoo/react-native-action-button for now.
