### ISSUE TITLE
Why my toolbar does not display properly?

### ISSUE THREAD

**Issue by AndoSuguru** [xotahal/react-native-material-ui#91]
![simulator screen shot feb 8 2017 20 17 11](https://cloud.githubusercontent.com/assets/9651260/22735095/9c38166c-ee3b-11e6-9270-f2844bec739e.png)

Commands executed to install:

```.sh
npm i react-native-material-ui --save
react-native link react-native-vector-icons
react-native run-ios
```

index.ios.js
```.js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { COLOR, ThemeProvider, Toolbar } from 'react-native-material-ui';
import { Navigator, NativeModules, StatusBar } from 'react-native';

const uiTheme = {
    palette: {
        primaryColor: COLOR.green500,
    },
    toolbar: {
        container: {
            height: 50,
        },
    },
};

const UIManager = NativeModules.UIManager;

const Container = (props) => {
  return (
    <View style={styles.container}>
      {props.children}
    </View>
  );
};

export default class Bar extends Component {
componentWillMount() {
        if (UIManager.setLayoutAnimationEnabledExperimental) {
            UIManager.setLayoutAnimationEnabledExperimental(true);
        }
    }

  render() {
    return (
      <ThemeProvider uiTheme={uiTheme}>
        <Container>
          <StatusBar backgroundColor="rgba(0, 0, 0, 0.2)" translucent />
          <View style={{ backgroundColor: COLOR.green500, height: 24 }} />
          <Container>
            <Toolbar
                key="toolbar"
                leftElement="menu"
                centerElement={'foo'}
            />
          </Container>
        </Container>
      </ThemeProvider>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
    // backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('Bar', () => Bar);

```

**Comment by xotahal** [comment]
Thank you - @AndoSuguru. Do you have the same problem with demo-app? https://github.com/xotahal/react-native-material-ui-demo-app

**Comment by HofmannZ** [comment]
I can confirm this bug, had to hold back from 1.7.0. I think the problem might be in the fact that styles are passed to the new LeftElement component, I'm not sure though.

**Comment by dipernaa** [comment]
I am getting the same issue across all platforms (iOS, Android, UWD)

**Comment by AndoSuguru** [comment]
@xotahal 
> Do you have the same problem with demo-app? 
No, it did not occur in the demo application.

**Comment by HofmannZ** [comment]
I see the demo app is running `react-native` version `0.39.2`. I have the issue on version `0.40.0`. I have some time tonight, so I will dive into this.

**Comment by NourDT** [comment]
So I ran into the same issue on but only on iOS and not on android, 
<img width="884" alt="screen shot 2017-02-10 at 2 54 43 pm" src="https://cloud.githubusercontent.com/assets/4145145/22817235/00a7878e-efa1-11e6-8c56-fa59aeddcdde.png">

how ever when trying to install the demo app, I had to `yarn update` in order to build as i was running into some errors previously with a node module 

What info can I provide to help you address this ?

**Comment by mortezaalizadeh** [comment]
Hey guys, have the same issue here, would be great if we can fix it. I will look at it later tonight on my fork version anyway. :)

**Comment by ryanstinson** [comment]
Temp fix for this is wrap the Toolbar in a View.
`<View style={{ flex: 1 }}>
          <View>
            <Toolbar style={{ zindex: -1 }}
              leftElement="menu"
              centerElement="Searchable"
              searchable={{
                autoFocus: true,
                placeholder: 'Search',
              }}
            />
          </View>`

**Comment by xotahal** [comment]
Hey guys, I've just fixed it - sorry for that. There missed just `{ overflow: 'hidden' }`

It's fixed in master. I'll publish it in next release - 1.8.0

**Comment by AndoSuguru** [comment]
thx!!
