### ISSUE TITLE
[Toolbar Search] Remove backgroundColor on icons

### ISSUE THREAD

**Issue by iamkyleee** [xotahal/react-native-material-ui#96]
**Not Searching**
![image](https://cloud.githubusercontent.com/assets/7822506/23237009/503f8d6e-f910-11e6-8b3b-8d2b410b321f.png)

**Search Button Clicked**
![image](https://cloud.githubusercontent.com/assets/7822506/23236985/430d4136-f910-11e6-8be4-5b86a693ff6d.png)

I'm using RN 0.41.2 & RNMUI 1.8.0

**Comment by simsim0709** [comment]
@iamkyleee Can I see your code?
It doesn't happen to me, though.

**Comment by xotahal** [comment]
Done https://github.com/xotahal/react-native-material-ui/releases/tag/v1.10.0
